# Generated by Django 5.1.15 on 2026-06-03 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=100, verbose_name='Nom (UZ)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Nom (EN)')),
                ('name_ru', models.CharField(blank=True, max_length=100, verbose_name='Nom (RU)')),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['name_uz'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'Teg',
                'verbose_name_plural': 'Teglar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('title_uz', models.CharField(max_length=255, verbose_name='Sarlavha (UZ)')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Sarlavha (EN)')),
                ('title_ru', models.CharField(blank=True, max_length=255, verbose_name='Sarlavha (RU)')),
                ('content_uz', models.TextField(blank=True, verbose_name='Kontent (UZ)')),
                ('content_en', models.TextField(blank=True, verbose_name='Kontent (EN)')),
                ('content_ru', models.TextField(blank=True, verbose_name='Kontent (RU)')),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/covers/', verbose_name='Muqova rasmi')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('published', 'Chop etilgan')], default='draft', max_length=10, verbose_name='Holat')),
                ('language', models.CharField(choices=[('uz', "O'zbekcha"), ('en', 'English'), ('ru', 'Русский')], default='uz', max_length=2, verbose_name='Asosiy til')),
                ('read_time', models.PositiveIntegerField(default=0, verbose_name="O'qish vaqti (daqiqa)")),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Chop etilgan vaqt')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category', verbose_name='Kategoriya')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='blog.tag', verbose_name='Teglar')),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Maqolalar',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
