# Generated by Django 5.1.15 on 2026-06-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('telegram', 'Telegram'), ('instagram', 'Instagram'), ('twitter', 'X (Twitter)'), ('youtube', 'YouTube'), ('facebook', 'Facebook'), ('email', 'Email'), ('website', 'Veb-sayt'), ('other', 'Boshqa')], default='other', max_length=20, verbose_name='Platforma')),
                ('label', models.CharField(blank=True, max_length=50, verbose_name='Nom (ixtiyoriy)')),
                ('url', models.CharField(help_text="To'liq URL yoki mailto:email", max_length=300, verbose_name='Havola')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Ijtimoiy tarmoq',
                'verbose_name_plural': 'Ijtimoiy tarmoqlar',
                'ordering': ['order', 'id'],
            },
        ),
    ]
