# Generated by Django 5.1.15 on 2026-06-03 14:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('title_uz', models.CharField(max_length=300, verbose_name='Sarlavha (UZ)')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='Sarlavha (EN)')),
                ('title_ru', models.CharField(blank=True, max_length=300, verbose_name='Sarlavha (RU)')),
                ('abstract_uz', models.TextField(blank=True, verbose_name='Annotatsiya (UZ)')),
                ('abstract_en', models.TextField(blank=True, verbose_name='Annotatsiya (EN)')),
                ('abstract_ru', models.TextField(blank=True, verbose_name='Annotatsiya (RU)')),
                ('work_type', models.CharField(choices=[('thesis', 'Tezis'), ('course', 'Kurs ishi'), ('dgu', 'DGU (amaliyot hisoboti)'), ('article', 'Ilmiy maqola'), ('conference', 'Konferensiya maqolasi')], max_length=20, verbose_name='Tur')),
                ('year', models.PositiveIntegerField(verbose_name='Yil')),
                ('language', models.CharField(choices=[('uz', "O'zbekcha"), ('en', 'English'), ('ru', 'Русский')], default='uz', max_length=2, verbose_name='Til')),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), blank=True, default=list, size=None, verbose_name="Kalit so'zlar")),
                ('authors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=120), blank=True, default=list, size=None, verbose_name='Mualliflar')),
                ('supervisor', models.CharField(blank=True, max_length=200, verbose_name='Rahbar')),
                ('file', models.FileField(blank=True, null=True, upload_to='academic/', verbose_name='Fayl (PDF)')),
                ('is_full_text_public', models.BooleanField(default=False, verbose_name="To'liq matn ochiq")),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar")),
                ('downloads_count', models.PositiveIntegerField(default=0, verbose_name='Yuklab olishlar')),
            ],
            options={
                'verbose_name': 'Ilmiy ish',
                'verbose_name_plural': 'Ilmiy ishlar',
                'ordering': ['-year', '-created_at'],
            },
        ),
    ]
