# Generated by Django 5.1.15 on 2026-06-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicwork',
            name='certificate_url',
            field=models.CharField(blank=True, max_length=300, verbose_name='Sertifikat rasmi'),
        ),
        migrations.AddField(
            model_name='academicwork',
            name='diploma_url',
            field=models.CharField(blank=True, max_length=300, verbose_name='Diplom rasmi'),
        ),
        migrations.AddField(
            model_name='academicwork',
            name='doi',
            field=models.URLField(blank=True, verbose_name='DOI havolasi'),
        ),
        migrations.AddField(
            model_name='academicwork',
            name='openaire_url',
            field=models.URLField(blank=True, verbose_name='OpenAIRE havolasi'),
        ),
        migrations.AddField(
            model_name='academicwork',
            name='source_url',
            field=models.URLField(blank=True, verbose_name='Nashr / manba havolasi'),
        ),
    ]
