# Generated by Django 5.1.15 on 2026-06-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_academicwork_certificate_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicwork',
            name='work_type',
            field=models.CharField(choices=[('thesis', 'Tezis'), ('course', 'Kurs ishi'), ('dgu', 'DGU (amaliyot hisoboti)'), ('article', 'Ilmiy maqola'), ('conference', 'Konferensiya maqolasi'), ('certificate', 'Sertifikat / Yutuq')], max_length=20, verbose_name='Tur'),
        ),
    ]
