# Generated by Django 5.1.15 on 2026-06-03 14:12

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description_uz', models.TextField(blank=True, verbose_name='Tavsif (UZ)')),
                ('description_en', models.TextField(blank=True, verbose_name='Tavsif (EN)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Tavsif (RU)')),
                ('technologies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None, verbose_name='Texnologiyalar')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub havola')),
                ('demo_url', models.URLField(blank=True, verbose_name='Live Demo havola')),
                ('project_type', models.CharField(choices=[('pet', 'Pet Project'), ('work', 'Work Project'), ('opensource', 'Open Source')], default='pet', max_length=20, verbose_name='Loyiha turi')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('completed', 'Yakunlangan'), ('archived', 'Arxiv')], default='active', max_length=20, verbose_name='Status')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Tanlangan (featured)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Loyiha',
                'verbose_name_plural': 'Loyihalar',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Rasm')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Izoh')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.project', verbose_name='Loyiha')),
            ],
            options={
                'verbose_name': 'Loyiha rasmi',
                'verbose_name_plural': 'Loyiha rasmlari',
                'ordering': ['order'],
            },
        ),
    ]
