# Generated by Django 5.1.15 on 2026-06-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_private',
            field=models.BooleanField(default=False, help_text="Belgilansa, saytda 'private — ruxsat etilganlar kiradi' ogohlantirishi chiqadi", verbose_name='Private repo'),
        ),
    ]
