# Generated by Django 5.1.15 on 2026-06-03 14:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200, verbose_name='Kompaniya')),
                ('position', models.CharField(max_length=200, verbose_name='Lavozim')),
                ('description_uz', models.TextField(blank=True, verbose_name='Tavsif (UZ)')),
                ('description_en', models.TextField(blank=True, verbose_name='Tavsif (EN)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Tavsif (RU)')),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(blank=True, help_text="Bo'sh = hozirgi ish", null=True, verbose_name='Tugash sanasi')),
                ('technologies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None, verbose_name='Texnologiyalar')),
                ('responsibilities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None, verbose_name='Vazifalar')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Ish tajribasi',
                'verbose_name_plural': 'Ish tajribalari',
                'ordering': ['order', '-start_date'],
            },
        ),
    ]
