# Generated by Django 5.1.15 on 2026-06-03 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nom')),
                ('category', models.CharField(choices=[('backend', 'Backend'), ('database', 'Database'), ('devops', 'DevOps'), ('tools', 'Tools'), ('design', 'Design'), ('other', 'Other')], default='other', max_length=20, verbose_name='Kategoriya')),
                ('icon_url', models.URLField(blank=True, verbose_name='Ikonka URL')),
                ('proficiency_level', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Daraja (1-100)')),
                ('years_experience', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Tajriba (yil)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': "Ko'nikma",
                'verbose_name_plural': "Ko'nikmalar",
                'ordering': ['category', 'order', '-proficiency_level'],
            },
        ),
    ]
